@URL = http://localhost:8080

### health
GET {{URL}}/health

### auth
GET {{URL}}/auth

### auth post
POST {{URL}}/auth
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### create post
POST {{URL}}/post
Content-Type: application/json

{
  "Title": "example",
  "Content": "This is an example."
}

